title: "Bossy Paws Rescue"
tagline: "Animals Are Our Mission"
description: "Bossy Paws is an entirely foster based rescue. Our amazing team of volunteers are committed to helping animals. We believe that these beautiful souls deserve to be in loving homes."
collections:
  - events
